#!/bin/bash

#if test -z $GIT_URL; then
#  echo 'Error. GIT_URL environment variable is not setted up.' > /dev/stderr
#  return 1
#fi

set -x

groupadd ci

if test ! -d /srv/.git; then
  chgrp -R ci /srv
  chmod -R g+rw /srv
  chmod g+s `find /srv -type d`
  cd /srv
  git init --shared=all
  git config init.defaultBranch master
  git config receive.denyCurrentBranch ignore
  cp /usr/bin/post-receive /srv/.git/hooks/post-receive
fi

echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

for developer in `ls /var/team`
do
  developer=`basename $developer`
  useradd -s /usr/bin/git-shell -m $developer
  # https://github.com/camptocamp/puppet-accounts/issues/35#issuecomment-770422222
  usermod -p '*' $developer
  usermod -aG docker,sudo,ci $developer
  mkdir /home/$developer/.ssh
  cat /var/team/$developer >> /home/$developer/.ssh/authorized_keys
  chmod 700 /home/$developer/.ssh
  # chmod 644 /home/$developer/.ssh/id_rsa.pub
  # chmod 600 /home/$developer/.ssh/id_rsa
  chmod 600 /home/$developer/.ssh/authorized_keys
  chown -R $developer:$developer /home/$developer/.ssh
done

set +x

/usr/sbin/sshd -D -e
