#!/usr/bin/env bash

GIT_WORK_TREE="/srv" GIT_DIR="/srv/.git" sudo --preserve-env git reset --hard master  || \
  echo 'Error, git reset.' > /dev/stderr
GIT_WORK_TREE="/srv" GIT_DIR="/srv/.git" sudo --preserve-env git checkout master || \
  echo 'Error, git checkout.' > /dev/stderr
if test -f /srv/Makefile; then
  cd /srv && sudo make
fi
