#!/usr/bin/env bash

GIT_WORKTREE="/srv" GIT_DIR="/srv/.git" git reset --hard master  || \
  echo 'Error, git reset.' > /dev/stderr
GIT_WORKTREE="/srv" GIT_DIR="/srv/.git" git checkout master || \
  echo 'Error, git checkout.' > /dev/stderr

if test -f /srv/Makefile; then
  /srv/Makefile
fi
